name: Remove Actions Cache
on:
    workflow_dispatch


jobs:
    clear-cache:
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
        
        steps:
          - name: Clear Cache
            env:
              GH_TOKEN: ${{ github.token }}
              GH_REPO: ${{ github.repository }}
            run: |
                keys=$(gh cache list --limit 100 --json key --jq '.[].key')
                
                if [ -z "$keys" ]; then
                    echo "No chaches found"
                    exit 0
                fi

                for key in $keys; do
                    echo "Deleting cache with Name: $key"
                    gh cache delete "$key"
                done
