name: Remove Actions Cache
on:
    workflow_dispatch


jobs:
    clear-cache:
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
        
        steps:
          - name: Clear Cache
            env:
              GH_TOKEN: ${{ github.token }}
              GH_REPO: ${{ github.repository }}
            run: |
                ids=$(gh cache list --limit 100 --json id --jq '.[].id')
                
                if [ -z "$ids"]; then
                    echo "No caches found"
                    exit 0
                fi

                for id in $ids; do
                    echo "Deleting cache with ID: $id"
                    gh cache delete "$id"
                done
